name: Deploy to Server

on:
  push:
    branches:
      - main  # Выполнять действие только при пуше в ветку main (вы можете изменить ветку при необходимости)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y sshpass

    - name: Deploy files to server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > key
        chmod 600 key
        rsync -avz -e "ssh -i key -o StrictHostKeyChecking=no" --exclude='.git*' ./ $SSH_USER@$SSH_HOST:/htdocs/back.turkcezormu.com/
